# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-09 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignPermissions',
            fields=[
                ('idAssignPermissions', models.AutoField(primary_key=True, serialize=False)),
                ('codeAssign', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doors',
            fields=[
                ('idDoors', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('state', models.IntegerField()),
                ('codeDoor', models.CharField(max_length=45, null=True, unique=True)),
                ('image', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False)),
                ('nameRol', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('numberDocument', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('lastName', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=75, unique=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtualkeyapirest.Rol')),
            ],
        ),
        migrations.AddField(
            model_name='assignpermissions',
            name='door',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtualkeyapirest.Doors'),
        ),
        migrations.AddField(
            model_name='assignpermissions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtualkeyapirest.User'),
        ),
    ]
