# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-06 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualkeyapirest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignpermissions',
            name='dateAssign',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
